### ISSUE TITLE
Would it be possible to use this inside Unity game engine?

### ISSUE THREAD

**Issue by SkutteOleg** [DarthAffe/StableDiffusion.NET#3]
I think Unity would be a good use case for a tool like this.

**Comment by DarthAffe** [comment]
I don't know that much about Unity, but as far as I know, the issue is, that they still use a quite old .NET version based on mono which lacks a lot of the things used here.
Until they decide to move on to a current .NET this would most likely require a specific implementation for Unity, which is not in the scope of this library here.
